name:                some-utils
version:             0.5.0.0
homepage:            http://dev.quietjoon.net/projects/some-utils.html
github:              "QuietJoon/some-utils"
license:             BSD3
category:            Data
author:              "YongJoon Joe"
maintainer:          "developer+some-utils@quietjoon.net"
copyright:           2014-2019 YongJoon Joe

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Some utility functions
description:         Please see the README on GitHub at <https://github.com/QuietJoon/some-utils#readme>

dependencies:
- base >= 4.7
- text
- directory

library:
  source-dirs: src
  other-modules: []

tests:
  basic-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - some-utils
    - HUnit
    - QuickCheck
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
